#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

char findTheDifference(char *s, char *t)
{
	int *s_freq = calloc(26, sizeof(int));
	int *t_freq = calloc(26, sizeof(int));
	int i, s_len = strlen(s), t_len = strlen(t);
	char sol = 0;

	if (s == NULL || t == NULL)
	{
		return sol;
	}

	// Update s's frequency array accordingly.
	for (i = 0; i < s_len; i++)
	{
		s_freq[s[i] - 97]++;
	}

	// Update t's frequency array accordingly.
	for (i = 0; i < 26; i++)
	{
		t_freq[t[i] - 97]++;
	}

	// Compare frequency arrays, return appropriate character when they differ.
	for (i = 0; i < 26; i++)
	{
		if (s_freq[i] != t_freq[i])
		{
			sol = i + 97;
		}
	}

	// Clean up.
	free(s_freq);
	free(t_freq);

	return sol;
}
